sudo: false
dist: xenial
language: python

env:
  - SH=bash

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

cache:
  pip: true

install:
  - "pip install -r rfgb/tests/requirements.txt"

script:
  - coverage run rfgb/tests/tests.py

before_install:
  pip install codecov

after_success:
  codecov
